export const WATTSWAP_HACKNIGHT_ABI = {
    address: "0x76601d78248a5d4e63d8ce40822897486df5f72e239991720d72810b97398b37",
    name: "wattswap_hacknight",
    friends: [],
    exposed_functions: [
      {
        name: "confirm",
        visibility: "public",
        is_entry: true,
        is_view: false,
        generic_type_params: [],
        params: ["&signer", "u64"],
        return: [],
      },
      {
        name: "create_swap",
        visibility: "public",
        is_entry: true,
        is_view: false,
        generic_type_params: [],
        params: ["&signer", "u64", "u64", "u64", "u64"],
        return: [],
      },
      {
        name: "get_active_swaps",
        visibility: "public",
        is_entry: false,
        is_view: true,
        generic_type_params: [],
        params: ["address"],
        return: [
          "vector<0x76601d78248a5d4e63d8ce40822897486df5f72e239991720d72810b97398b37::wattswap_hacknight::WattSwap>",
        ],
      },
      {
        name: "get_all_active_listings",
        visibility: "public",
        is_entry: false,
        is_view: true,
        generic_type_params: [],
        params: ["address"],
        return: [
          "vector<0x76601d78248a5d4e63d8ce40822897486df5f72e239991720d72810b97398b37::wattswap_hacknight::WattSwap>",
        ],
      },
      {
        name: "get_join_date",
        visibility: "public",
        is_entry: false,
        is_view: true,
        generic_type_params: [],
        params: ["address"],
        return: ["u64"],
      },
      {
        name: "get_swap_details",
        visibility: "public",
        is_entry: false,
        is_view: true,
        generic_type_params: [],
        params: ["address", "u64"],
        return: ["0x76601d78248a5d4e63d8ce40822897486df5f72e239991720d72810b97398b37::wattswap_hacknight::WattSwap"],
      },
      {
        name: "get_swaps",
        visibility: "public",
        is_entry: false,
        is_view: true,
        generic_type_params: [],
        params: ["address"],
        return: [
          "vector<0x76601d78248a5d4e63d8ce40822897486df5f72e239991720d72810b97398b37::wattswap_hacknight::WattSwap>",
        ],
      },
      {
        name: "initialize_swaps",
        visibility: "public",
        is_entry: true,
        is_view: false,
        generic_type_params: [],
        params: ["&signer"],
        return: [],
      },
      {
        name: "purchase",
        visibility: "public",
        is_entry: true,
        is_view: false,
        generic_type_params: [],
        params: ["&signer", "address", "u64", "u64"],
        return: [],
      },
      {
        name: "remove_listing",
        visibility: "public",
        is_entry: true,
        is_view: false,
        generic_type_params: [],
        params: ["&signer", "u64"],
        return: [],
      },
      {
        name: "withdraw_expired_escrow",
        visibility: "public",
        is_entry: true,
        is_view: false,
        generic_type_params: [],
        params: ["&signer", "address", "u64"],
        return: [],
      },
    ],
    structs: [
      {
        name: "ActiveListings",
        is_native: false,
        is_event: false,
        abilities: ["key"],
        generic_type_params: [],
        fields: [
          {
            name: "listings",
            type: "vector<0x76601d78248a5d4e63d8ce40822897486df5f72e239991720d72810b97398b37::wattswap_hacknight::WattSwap>",
          },
        ],
      },
      {
        name: "ConfirmEvent",
        is_native: false,
        is_event: false,
        abilities: ["drop", "store"],
        generic_type_params: [],
        fields: [
          { name: "seller", type: "address" },
          { name: "swap_id", type: "u64" },
          { name: "timestamp", type: "u64" },
        ],
      },
      {
        name: "Escrow",
        is_native: false,
        is_event: false,
        abilities: ["store", "key"],
        generic_type_params: [],
        fields: [
          { name: "buyer", type: "address" },
          { name: "seller", type: "address" },
          { name: "swap_id", type: "u64" },
          { name: "apt_amount", type: "u64" },
          { name: "expiry_timestamp", type: "u64" },
          { name: "resource_cap", type: "0x1::account::SignerCapability" },
        ],
      },
      {
        name: "EscrowExpiredEvent",
        is_native: false,
        is_event: false,
        abilities: ["drop", "store"],
        generic_type_params: [],
        fields: [
          { name: "buyer", type: "address" },
          { name: "seller", type: "address" },
          { name: "swap_id", type: "u64" },
          { name: "timestamp", type: "u64" },
        ],
      },
      {
        name: "ListingRemovedEvent",
        is_native: false,
        is_event: false,
        abilities: ["drop", "store"],
        generic_type_params: [],
        fields: [
          { name: "seller", type: "address" },
          { name: "swap_id", type: "u64" },
          { name: "timestamp", type: "u64" },
        ],
      },
      {
        name: "PurchaseEvent",
        is_native: false,
        is_event: false,
        abilities: ["drop", "store"],
        generic_type_params: [],
        fields: [
          { name: "buyer", type: "address" },
          { name: "seller", type: "address" },
          { name: "swap_id", type: "u64" },
          { name: "apt_amount", type: "u64" },
          { name: "timestamp", type: "u64" },
        ],
      },
      {
        name: "SwapCreatedEvent",
        is_native: false,
        is_event: false,
        abilities: ["drop", "store"],
        generic_type_params: [],
        fields: [
          { name: "seller", type: "address" },
          { name: "swap_id", type: "u64" },
          { name: "watt_amount", type: "u64" },
          { name: "apt_price", type: "u64" },
          { name: "timestamp", type: "u64" },
        ],
      },
      {
        name: "WattSwap",
        is_native: false,
        is_event: false,
        abilities: ["copy", "drop", "store", "key"],
        generic_type_params: [],
        fields: [
          { name: "id", type: "u64" },
          { name: "seller", type: "address" },
          { name: "buyers", type: "vector<address>" },
          { name: "amounts_bought", type: "vector<u64>" },
          { name: "watt_amount", type: "u64" },
          { name: "min_watt_amount", type: "u64" },
          { name: "max_watt_amount", type: "u64" },
          { name: "apt_price_per_watt", type: "u64" },
          { name: "is_active", type: "bool" },
          { name: "creation_timestamp", type: "u64" },
        ],
      },
      {
        name: "WattSwapEvents",
        is_native: false,
        is_event: false,
        abilities: ["key"],
        generic_type_params: [],
        fields: [
          {
            name: "swap_created_events",
            type: "0x1::event::EventHandle<0x76601d78248a5d4e63d8ce40822897486df5f72e239991720d72810b97398b37::wattswap_hacknight::SwapCreatedEvent>",
          },
          {
            name: "purchase_events",
            type: "0x1::event::EventHandle<0x76601d78248a5d4e63d8ce40822897486df5f72e239991720d72810b97398b37::wattswap_hacknight::PurchaseEvent>",
          },
          {
            name: "confirm_events",
            type: "0x1::event::EventHandle<0x76601d78248a5d4e63d8ce40822897486df5f72e239991720d72810b97398b37::wattswap_hacknight::ConfirmEvent>",
          },
          {
            name: "listing_removed_events",
            type: "0x1::event::EventHandle<0x76601d78248a5d4e63d8ce40822897486df5f72e239991720d72810b97398b37::wattswap_hacknight::ListingRemovedEvent>",
          },
          {
            name: "escrow_events",
            type: "0x1::event::EventHandle<0x76601d78248a5d4e63d8ce40822897486df5f72e239991720d72810b97398b37::wattswap_hacknight::EscrowExpiredEvent>",
          },
        ],
      },
      {
        name: "WattSwaps",
        is_native: false,
        is_event: false,
        abilities: ["key"],
        generic_type_params: [],
        fields: [
          {
            name: "swaps",
            type: "vector<0x76601d78248a5d4e63d8ce40822897486df5f72e239991720d72810b97398b37::wattswap_hacknight::WattSwap>",
          },
          { name: "swap_count", type: "u64" },
          { name: "join_date", type: "u64" },
        ],
      },
    ],
  } as const;
  